<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-6T0AJC6" failures="1" tests="2" name="tests.LoginTest" time="3.997" errors="0" timestamp="2023-07-17T15:00:13 ART" skipped="0">
  <testcase classname="tests.LoginTest" name="loginValido_01" time="2.362">
    <system-out>
      <![CDATA[Ingresar usuario: standard_user
Ingresando contrase単a]]>
    </system-out>
  </testcase> <!-- loginValido_01 -->
  <testcase classname="tests.LoginTest" name="loginFallido_02" time="1.635">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at tests.LoginTest.loginFallido_02(LoginTest.java:47)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
    <system-out>
      <![CDATA[Ingresar usuario: standard_user
Ingresando contrase単a]]>
    </system-out>
  </testcase> <!-- loginFallido_02 -->
  <system-out>
    <![CDATA[====================================================
TEST METHOD: loginValido_01
Parameters:
password : secret_sauce
username : standard_user
====================================================
Ingresar usuario: standard_user
Ingresando contrase単a
---------------
Finaliza loginValido_01
---------------
====================================================
TEST METHOD: loginFallido_02
Parameters:
password : secret_salsa
username : standard_user
====================================================
Ingresar usuario: standard_user
Ingresando contrase単a
---------------
Finaliza loginFallido_02


Result: FAIL
---------------
Ingresar usuario: standard_user
Ingresar password
Agregar 3 a carrito
Ingresar usuario: standard_user
Ingresar password
Comparando valor inicial con el valor final]]>
  </system-out>
</testsuite> <!-- tests.LoginTest -->
